export const TOKEN_KEY = 'token'
export const LOGIN_HOST = 'https://website-backend.computiq.tech'
export const LOGIN_PATH = '/api/academy/auth/login'
export const GET_PRODUCTS_HOST = 'https://fakestoreapi.com'
export const GET_PRODUCTS_PATH = '/products'